name: LotteryApp 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ethereum/package-lock.json
    - name: Setup
      run: npm ci
      run: node compile_lottery
      run: node deploy
      working-directory: ethereum
    - name: Test
      run: npm run test
      working-directory: ethereum